// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjzw8v2EzXiyHmf6RgEXNoV-ABLnlkRrc',
    appId: '1:717033580983:web:67ac644e2d4814157a2032',
    messagingSenderId: '717033580983',
    projectId: 'aplicativo-rpg-dicell',
    authDomain: 'aplicativo-rpg-dicell.firebaseapp.com',
    storageBucket: 'aplicativo-rpg-dicell.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCkZ5jjPzIpbNF9R02x7SKvLTcSCnZOi4',
    appId: '1:717033580983:android:03297c3b5dade3677a2032',
    messagingSenderId: '717033580983',
    projectId: 'aplicativo-rpg-dicell',
    storageBucket: 'aplicativo-rpg-dicell.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPXsGlWGC6-mm1ApRXLTaD9Sppw7qX2M8',
    appId: '1:717033580983:ios:4d3b59bff74c020c7a2032',
    messagingSenderId: '717033580983',
    projectId: 'aplicativo-rpg-dicell',
    storageBucket: 'aplicativo-rpg-dicell.firebasestorage.app',
    iosBundleId: 'com.example.aplicativoRpg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPXsGlWGC6-mm1ApRXLTaD9Sppw7qX2M8',
    appId: '1:717033580983:ios:4d3b59bff74c020c7a2032',
    messagingSenderId: '717033580983',
    projectId: 'aplicativo-rpg-dicell',
    storageBucket: 'aplicativo-rpg-dicell.firebasestorage.app',
    iosBundleId: 'com.example.aplicativoRpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjzw8v2EzXiyHmf6RgEXNoV-ABLnlkRrc',
    appId: '1:717033580983:web:45fc63fbd89e6c167a2032',
    messagingSenderId: '717033580983',
    projectId: 'aplicativo-rpg-dicell',
    authDomain: 'aplicativo-rpg-dicell.firebaseapp.com',
    storageBucket: 'aplicativo-rpg-dicell.firebasestorage.app',
  );
}
